// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DBGateway(arg1, arg2, arg3) {
  return window['go']['main']['App']['DBGateway'](arg1, arg2, arg3);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetEventSnapshot() {
  return window['go']['main']['App']['GetEventSnapshot']();
}

export function GetLogSnapshot() {
  return window['go']['main']['App']['GetLogSnapshot']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function HealthCheck() {
  return window['go']['main']['App']['HealthCheck']();
}

export function LoadContext(arg1) {
  return window['go']['main']['App']['LoadContext'](arg1);
}

export function MCPGateway(arg1) {
  return window['go']['main']['App']['MCPGateway'](arg1);
}

export function ProxyRequest(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ProxyRequest'](arg1, arg2, arg3, arg4);
}

export function Restart() {
  return window['go']['main']['App']['Restart']();
}

export function StoreContext(arg1) {
  return window['go']['main']['App']['StoreContext'](arg1);
}

export function TrustCert() {
  return window['go']['main']['App']['TrustCert']();
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}
