// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DBGateway(arg1, arg2, arg3) {
  return window['go']['main']['App']['DBGateway'](arg1, arg2, arg3);
}

export function FSGateway(arg1, arg2) {
  return window['go']['main']['App']['FSGateway'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetEventSnapshot() {
  return window['go']['main']['App']['GetEventSnapshot']();
}

export function GetLogSnapshot() {
  return window['go']['main']['App']['GetLogSnapshot']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function HealthCheck() {
  return window['go']['main']['App']['HealthCheck']();
}

export function HprofAnalyzeStream(arg1, arg2) {
  return window['go']['main']['App']['HprofAnalyzeStream'](arg1, arg2);
}

export function HprofGateway(arg1, arg2, arg3) {
  return window['go']['main']['App']['HprofGateway'](arg1, arg2, arg3);
}

export function LoadContext(arg1) {
  return window['go']['main']['App']['LoadContext'](arg1);
}

export function MCPGateway(arg1) {
  return window['go']['main']['App']['MCPGateway'](arg1);
}

export function ProxyRequest(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ProxyRequest'](arg1, arg2, arg3, arg4);
}

export function Restart() {
  return window['go']['main']['App']['Restart']();
}

export function SFTPDownloadCancel(arg1) {
  return window['go']['main']['App']['SFTPDownloadCancel'](arg1);
}

export function SFTPDownloadStart(arg1, arg2, arg3) {
  return window['go']['main']['App']['SFTPDownloadStart'](arg1, arg2, arg3);
}

export function SFTPUploadCancel(arg1) {
  return window['go']['main']['App']['SFTPUploadCancel'](arg1);
}

export function SFTPUploadChunk(arg1, arg2) {
  return window['go']['main']['App']['SFTPUploadChunk'](arg1, arg2);
}

export function SFTPUploadFinish(arg1) {
  return window['go']['main']['App']['SFTPUploadFinish'](arg1);
}

export function SFTPUploadStart(arg1, arg2, arg3) {
  return window['go']['main']['App']['SFTPUploadStart'](arg1, arg2, arg3);
}

export function SSHCloseTerminal(arg1) {
  return window['go']['main']['App']['SSHCloseTerminal'](arg1);
}

export function SSHGateway(arg1, arg2) {
  return window['go']['main']['App']['SSHGateway'](arg1, arg2);
}

export function SSHOpenTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['SSHOpenTerminal'](arg1, arg2, arg3);
}

export function SSHResize(arg1, arg2, arg3) {
  return window['go']['main']['App']['SSHResize'](arg1, arg2, arg3);
}

export function SSHStdin(arg1, arg2) {
  return window['go']['main']['App']['SSHStdin'](arg1, arg2);
}

export function SSHSubmitKIResponse(arg1, arg2) {
  return window['go']['main']['App']['SSHSubmitKIResponse'](arg1, arg2);
}

export function StoreContext(arg1) {
  return window['go']['main']['App']['StoreContext'](arg1);
}

export function TrustCert() {
  return window['go']['main']['App']['TrustCert']();
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}
