// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetVersion():Promise<string>;

export function Maximise():Promise<void>;

export function Minimise():Promise<void>;

export function ToggleFullscreen():Promise<void>;

export function ToggleMaximise():Promise<void>;

export function UnFullscreen():Promise<void>;

export function UnMaximise():Promise<void>;

export function UnMinimise():Promise<void>;
