// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function Maximise() {
  return window['go']['main']['App']['Maximise']();
}

export function Minimise() {
  return window['go']['main']['App']['Minimise']();
}

export function ToggleFullscreen() {
  return window['go']['main']['App']['ToggleFullscreen']();
}

export function ToggleMaximise() {
  return window['go']['main']['App']['ToggleMaximise']();
}

export function UnFullscreen() {
  return window['go']['main']['App']['UnFullscreen']();
}

export function UnMaximise() {
  return window['go']['main']['App']['UnMaximise']();
}

export function UnMinimise() {
  return window['go']['main']['App']['UnMinimise']();
}
